spring.application.name=Restaurant-Management-Project

# Application name
spring.datasource.url=jdbc:postgresql://localhost:5432/Ommurhe

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/home
spring.datasource.username=postgres
spring.datasource.password=Pass@123

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
